### ISSUE TITLE
The Shell setup link is giving a 404 error

### ISSUE THREAD

**Issue by wgriffa** [LibraryCarpentry/lc-shell#1]
Hi if you start from, https://librarycarpentry.github.io/lc-shell/
and then click on the setup (http://librarycarpentry.github.io/lcshell/setup/) link you get....

404
File not found
The site configured at this address does not contain the requested file.
If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.
Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus

**Comment by libcce** [comment]
Link updated from lcshell/setup to lc-shell/setup https://github.com/LibraryCarpentry/lc-shell/commit/ee87452167226846e7b4d20e7fd30a39282d074e
