### ISSUE TITLE
Filename change recommendation

### ISSUE THREAD

**Issue by mrosed** [LibraryCarpentry/lc-shell#100]
One of the files in the shell-lesson folder is a JSON file called "000003160_01_text." The long string of zeros is difficult to type while live coding. Perhaps a few (or all of) the zeroes could be removed from the name of this file. Thanks!

**Comment by jyssy** [comment]
How would I reupload an edited ZIP file here with an edited json file (with a shorter name)? I will also need to make sure any reference to the file in the instructions is correct and the same. thanks for your guidance.

**Comment by jyssy** [comment]
I submitted a PR and Tim Dennis will upload the zip with the new file names

**Comment by jt14den** [comment]
Thanks @mrosed @jyssy and @alex-ball
