### ISSUE TITLE
Episode #4: Explanation and example differ

### ISSUE THREAD

**Issue by birgitfrenz** [LibraryCarpentry/lc-shell#106]
The explanation in the paragraph "Double-quoting variable substitutions" and the example above (writing a loop) differ in the order. The explanation says "The interpreter runs the command cp on a.doc, and then prints the filename to the screen". In the example the filename is printed first.

**Comment by jyssy** [comment]
Should be taken care of (switching the language in the description to reflect the rest of the description as well as the example above it).
