### ISSUE TITLE
`date` command in episode 5

### ISSUE THREAD

**Issue by ha0ye** [LibraryCarpentry/lc-shell#109]
per @aadoek

The unix `date` command takes different options on Mac OS (because Mac uses BSD command line utilities rather than GNU). For this reason some of the examples that use `date -I` (to return the system date in ISO-8601 format) don't work.

A suggested fix is to specify the full date format for Mac:
`date +%Y-%m-%d` instead.

**Comment by mharp** [comment]
This is indeed and issue (experienced in macOS Catalina) suggest including a notation our callout for Mac users.

**Comment by alex-ball** [comment]
Duplicate of #85.
