### ISSUE TITLE
Add details about remaining punctuation in 06-free-text

### ISSUE THREAD

**Issue by jcoliver** [LibraryCarpentry/lc-shell#11]
In option 1 (working with gulliver.txt), there is this line:

> Note: there are a few bits of punctuation in here - I’ve left these in deliberately as you should always bug fix! The internet is a always a good place to start searching for why this might have happened (something about the `punct` command we used…)

The remaining punctuation marks in the file appear to be curly (or "smart") quotes: “ and ‘ (and corresponding counterparts). Additional information should probably be provided. 
+ An easy way to identify that there _are_ still punctuation marks in the file. Note `grep [“‘”’] gulliver-final.txt` works but might be a little heavy-handed.
+ A little more guidance on investigating the issue (like what to search the Internet for other than `punct`). 

Migrated from data-lessons/library-shell-DEPRECATED#67

**Comment by libcce** [comment]
Sorry for the long delay in responding to this issue @jcoliver! I turned the note into a challenge. What do you think https://github.com/LibraryCarpentry/lc-shell/pull/70 ?

**Comment by dakane1** [comment]
Merged @libcce changes, will go ahead and close issue.  Sorry I didn't see this sooner, I didn't realize we now had 2 issues lists :-).
