### ISSUE TITLE
Small typos in "Navigating the filesystem" lesson

### ISSUE THREAD

**Issue by MikeSerafin** [LibraryCarpentry/lc-shell#112]
On https://librarycarpentry.org/lc-shell/02-navigating-the-filesystem/index.html - in the box "Getting help", second paragraph, Windows is not capitalized and shell is capitalized.

**Comment by rfbrown** [comment]
I've submitted a PR for this issue here: https://github.com/LibraryCarpentry/lc-shell/pull/129

**Comment by jt14den** [comment]
Thanks @rfbrown & @MikeSerafin
