### ISSUE TITLE
"ambiguous redirect" error with "date" variable in episode 5

### ISSUE THREAD

**Issue by egrguric** [LibraryCarpentry/lc-shell#114]
This relates to "Mining or Searching" here: [https://librarycarpentry.org/lc-shell/05-counting-mining/index.html](url)

This command throws two errors on macOS Mojave: 

``` bash
$ grep -iw revolution *.tsv > results/$(date -I)_JAiw-revolution.tsv
```

First error is documented in [this issue](https://github.com/LibraryCarpentry/lc-shell/issues/109). After solving for this by removing the -I it still throws this error: 

``` bash
-bash: results/$(date)_JAi-revolution.tsv: ambiguous redirect
```

One fix is to put quotes around $(date):

```bash
$ grep -iw revolution *.tsv > results/"$(date)"_JAiw-revolution.tsv
```

**Comment by alex-ball** [comment]
If you just remove the `-I` bit, your command will expand to something like this:

```bash
grep -iw revolution *.tsv > results/Mon  1 Jun 12:28:15 UTC 2020_JAiw-revolution.tsv
```

The spaces mean you are specifying six files there, hence "ambiguous redirect". You are right that the quotes fix the error (by effectively escaping the spaces), but you end up with a terrible file name. You really need the fix described in #109:

```bash
grep -iw revolution *.tsv > results/$(date "+%Y-%m-%d")_JAiw-revolution.tsv
```
