### ISSUE TITLE
Result for "echo "Library Carpentry is awesome!" not returning proper result without editing

### ISSUE THREAD

**Issue by mharp** [LibraryCarpentry/lc-shell#115]
Could not tell if this is an already reported issue.
Environment: macOS Catalina - iMac and MacAir

In episode [Working with files and directories /](https://github.com/LibraryCarpentry/lc-shell/blob/gh-pages/_episodes/03-working-with-files-and-folders.md) Using the echo command
`echo "Library Carpentry is awesome!"`

Returns a request for final quote:
`dquote>`

however the "!" (exclamation point) is truncated when final quote is added. 
`Library Carpentry is awesome`

Leaving a space between the exclamation point and the quote 
`$ echo "Library Carpentry is awesome! "`

produced correct result: 
`Library Carpentry is awesome!`

Is this an issue for anyone else?
---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

**Comment by alex-ball** [comment]
This is an example of code that is not portable between bash and zsh, the latter being the new default on Macs. Relates to #96.

The issue is that `!` is used (I think) to introduce a history-searching expression in zsh, which means it swallows the following double quote. You either have to escape it:

```bash
echo "Library Carpentry is awesome\!"
```

or use single quotes instead, so it is not interpreted as a special character.

**Comment by jt14den** [comment]
Thanks @alex-ball and @mharp!
