### ISSUE TITLE
"Pulling a text apart, counting word frequencies" in Working with free text

### ISSUE THREAD

**Issue by andreaswalker** [LibraryCarpentry/lc-shell#119]
https://librarycarpentry.org/lc-shell/06-free-text/index.html
`$ tr ' ' '\n' < gulliver-clean.txt | sort | uniq -c | sort -r > gulliver-final.txt`
should be
`$ tr ' ' '\n' < gulliver-clean.txt | sort | uniq -c | sort -rn > gulliver-final.txt`
for numerical counting; maybe we should also explain the -r flag?

**Comment by alex-ball** [comment]
The change to numerical sorting is proposed in PR #94. Thanks for confirming my thoughts on this.

I agree the `-r` flag ought to be explained somewhere, or explaining it could be an exercise/question to ask learners.

**Comment by jt14den** [comment]
Thanks @andreaswalker and @alex-ball!
