### ISSUE TITLE
'Automatically adding a date prefix' in 05-counting-mining.md

### ISSUE THREAD

**Issue by nichworby** [LibraryCarpentry/lc-shell#131]
'Solution' suggests using `date --help`. This only works for Windows users. `man date` should be added for OS/Linux users.

**Comment by alex-ball** [comment]
Not that this negates this issue in any way, but the GNU `date` command on Linux does have a `--help` option, so it is only the macOS X version that is affected.

**Comment by drkenyajones** [comment]
Having both windows and mac options available is helpful and will offer support for both users.
