### ISSUE TITLE
"Invalid option – o" in episode 5 out of date

### ISSUE THREAD

**Issue by alex-ball** [LibraryCarpentry/lc-shell#135]
In Episode 5, the callout "Invalid option – o?" says

> If you get an error message “invalid option – o” when running the above command, it means you use a version of grep that doesn’t support the -o flag. This is for instance the case with the version of grep that comes with Git Bash on Windows.

https://github.com/LibraryCarpentry/lc-shell/blob/2ab6df7c2975f8aed998023c97eee14249f1f8ff/_episodes/05-counting-mining.md#L612-L614

This was true when the callout was added (2 June 2017 in 1969f757) but someone may have been listening because it's not the case any longer. If I'm reading the right bit of source code, the option was added to Git Bash on Windows on 9 July 2018 in commit git-for-windows/git@9d8db06e, and first released in version v2.19.0-rc0.windows.1 on 21 Aug 2018.

The `-o` option is supported on [macOS](https://ss64.com/osx/grep.html) and in [GNU grep](https://ss64.com/bash/grep.html) (hence on Linux and in WSL shells on Windows 10), so does anyone know of any remaining greps that don't support `-o`?

Probably for now the best thing would be to put this warning in the past tense:

> This was the case with the version of grep that came with Git Bash on Windows before September 2018. Since the flag is not crucial to this lesson, please just relax and ignore the problem. If you want the flag in future, however, you could install another version of grep, perhaps by upgrading your version of Git Bash on Windows, or installing a Bash shell for Windows 10 using the Windows Subsystem for Linux.

But once we're comfortable that everyone has upgraded past Git Bash on Windows v2.18, I think this callout and the references to it could be removed.

**Comment by jt14den** [comment]
@alex-ball Thanks for figuring all this out! Since we ask learners to install the latest Git Bash on Windows and it's been a couple of years, I'd vote for removing the callout altogether. From my experience, most learners are brand new to bash and install Git Bash on Windows for the first time for the workshop.

**Comment by alex-ball** [comment]
I see this is also mentioned in the Instructor Notes. How about we remove it from the lesson text but update the Instructor Notes to say that if a learner has trouble with the -o flag, they should update their Git Bash for Windows? As you say, this is unlikely ever to come up again, but you can imagine there will be that one exceptional case...

**Comment by jt14den** [comment]
@alex-ball cool! Sounds good and it's def. good to keep in instructor notes for when it comes up.
