### ISSUE TITLE
Lesson 2 - description of shell appearance

### ISSUE THREAD

**Issue by alyssafahringer** [LibraryCarpentry/lc-shell#139]
In Lesson 2: Navigating the filesystem, it says:

`Let’s start by opening the shell. This likely results in seeing a black window with a cursor flashing next to a dollar sign.`

I use MacOS Catalina, and with the upgrade the default shell is now zsh rather than bash. I would note that some Mac users might see a white window and a dollar sign, or a white window, tilde, and percentage sign.

**Comment by kaitlinnewson** [comment]
Resolved in #161
