### ISSUE TITLE
Invalid Grep-o flag - Ep.5 Counting and Mining.md 

### ISSUE THREAD

**Issue by kristi-sara** [LibraryCarpentry/lc-shell#146]
Under the searching and mining portion of the lesson, the code:' _**grep -iwEo 'Cont[ae][cn]t' *.csv**_ ' (under Mining and Searching) has learners use the **grep -o** flag, however, some users have an older version of grep that does not recognize the flag and this can cause confusion among learners despite it being a legitimate flag. It would be appropriate to add a tip blurb explaining why this may happen (and how to fix it by installing a newer grep version) and I think it would reassure instructors and learners who are not aware of the issue.  We made this amendment in our library carpentry workshop and also split Counting and Mining into two separate lessons since it was so long (but thats a different circus). 

Counting and Mining Lesson Link: https://librarycarpentry.org/lc-shell/05-counting-mining/index.html 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

**Comment by alex-ball** [comment]
We used to have the warning of which you speak, but removed it because the older grep you refer to is quite old now: see Issue #135.

There is a note about this in the Instructor Notes:

> The `grep` on Git Bash for Windows prior to version 2.19.0 (September 2018) did not support the `-o` flag. If someone gets an error "invalid option -- o", they are most likely trying to use one of these older versions. They should probably just skip the exercises that use it and upgrade later.

Is the prevalence of the v2.18-and-earlier Git Bash for Windows greater than we anticipated?

**Comment by kaitlinnewson** [comment]
Closing this issue as the version of grep this applies to is quite old now - please feel free to reopen if this issue is still commonly occurring.

**Comment by kristi-sara** [comment]
oh yikes I forgot I even opened this 3 years ago. Surely grep has been updated...
