### ISSUE TITLE
Instructor Notes - typos?

### ISSUE THREAD

**Issue by madwarner99** [LibraryCarpentry/lc-shell#152]
Hi there!  This from a newbie, so I'm not sure if these are errors, but I'm finding them confusing.

https://librarycarpentry.org/lc-shell/guide/

1.  From the first line of the 3rd paragraph of the Overview section:
The third answer is, “Because it enables use of many domain-specific tools and compute resources researchers cannot access otherwise.” 
Should the word compute be computer?

2.  From the Teaching Notes section toward the bottom:

- We have to leave out many important things because of time constraints, including file permissions, job control, and SSH. If learners already understand the basic material, this can be covered instead using the online lessons as guidelines. These limitations also have follow-on consequences:

- It’s hard to discuss #! (shebang) without first discussing permissions, which we don’t do. #! is also pretty complicated, so even if we did discuss permissions, we probably still wouldn’t want to discuss #!.

- Installing Bash and a reasonable set of Unix commands on Windows always involves some fiddling and frustration. Please see the latest set of installation guidelines for advice, and try it out yourself before teaching a class.

- On Windows machines if nano hasn’t been properly installed with the Software Carpentry Windows Installer it is possible to use notepad as an alternative. There will be a GUI interface and line endings are treated differently, but otherwise, for the purposes of this lesson, notepad and nano can be used almost interchangeably.

- On Windows, it appears that: ..."

After "follow-on consequences:" I'm looking for a list of the consequences, but the bulleted list resumes.  Which if any of the following bullets apply to the above, or is the colon supposed to be a period?

**Comment by alex-ball** [comment]
1. This is a bit of computer science jargon, but "compute" is used a bit like "storage", that is, to refer to computation as a function or service that an organization provides. So "compute resource" refers to any service on which you can run a computational "job" and get a result back. (In some big data scenarios, you would never download the data and analyse it locally; instead you would send an analysis routine to where the data is held and get them to pass back the output.)

2. From what I can see, the immediately following point (about shebang) is a follow-on consequence of missing out an important thing (permissions). But none of the points after that seem to be. I also note that "Installing Bash and a reasonable set of Unix commands on Windows..." is repeated and expanded on in its own section below, so could probably be deleted from this list.
