### ISSUE TITLE
Instructor guides needed

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-shell#17]
I would like to see instructor guides developed for all Library Carpentry lessons. This could be a good sprint project. Librarians will probably like to have some guidance on how to teach what for many will be new material. Not sure what instructor guides should consist of? Then see some of the guides for Software Carpentry lessons, e.g. shell - http://swcarpentry.github.io/shell-novice/guide/, python - http://swcarpentry.github.io/python-novice-inflammation/guide/.

Guides like this help with context setting, things to remember to explain, and other useful info.

History of this issue: https://github.com/data-lessons/librarycarpentry/issues/27

**Comment by dakane1** [comment]
I would be willing to take a stab at this.

**Comment by dakane1** [comment]
Though it looks like one has already been created.  Does this issue need to be closed or are you looking for an update?

**Comment by libcce** [comment]
@dakane1 in the SQL lesson repo, we are looking at updating the instructor guide/notes, so I think its probably a good idea to do this. @jt14den @uom-nilani what do you think? And do you have notes to share?

**Comment by dakane1** [comment]
@libcce If I had notes I could start something, I haven't taught SQL yet so I don't have any insights of my own.

**Comment by jt14den** [comment]
I don't have notes on hand, but this issue is related to #51. Instructor notes for this lesson are mostly a copy of the SWC lesson, so reworking to correspond the LC lesson and experience of teaching would be good. I haven't had a chance to read them closely, but we are teaching the shell next month - so can look.

**Comment by libcce** [comment]
@jt14den my notes are largely based on yours so whatever you propose 👍

**Comment by libcce** [comment]
There is a guide. Issue https://github.com/LibraryCarpentry/lc-shell/issues/51 addresses updating the guide.
