### ISSUE TITLE
Desktop in OneDrive

### ISSUE THREAD

**Issue by aadoek** [LibraryCarpentry/lc-shell#180]
in recent Library and Software Carpentry workshops I noticed that the Setup instructions of this and other lessons present a problem to Microsoft OneDrive users.
The instruction is to install software and/or files **on the Desktop**.
Microsoft seems to have placed the Desktop in OneDrive. Things in OneDrive are not fully under the user's control. So at some points the participants are asked to do things that OneDrive doesn't allow.

**Comment by tobyhodges** [comment]
Thank you for reporting this issue, @aadoek 🙌 This is a perfect fit for [our wiki page on Configuration Problems and Solutions](https://github.com/carpentries/workshop-template/wiki/Configuration-Problems-and-Solutions#bash). I would like to provide more information about exactly what happens the first time such an error is encountered, to help people recognise the issue when it arises, but unfortunately I do not have access to a Windows system at the moment. 

I wonder if you are able to help me, by posting some more detail here about what the problem looks like e.g. what is the error message? When is it first encountered in the lesson?

**Comment by jmjamison** [comment]
I use windows on my own machine but don't use OneDrive so I haven't encountered this myself.  Usually I see this happen with work-issued laptops - setup without the user having admin privileges. I'm guessing that a user who has control of their own machine wouldn't have that problem.

UCLA is scheduling carpentry workshops for February.  We can keep an eye out for related examples then.

**Comment by jas58** [comment]
I created PR #215 recently when I tested this before teaching last week.  I chatted with Sarah Stevens about it, too.
@sstevens2

**Comment by jmjamison** [comment]
I just realized that this has actually bee closed: https://github.com/LibraryCarpentry/lc-shell/issues/180

**Comment by kaitlinnewson** [comment]
For more info - closed in https://github.com/LibraryCarpentry/lc-shell/pull/252
