### ISSUE TITLE
Bad Link to Putty

### ISSUE THREAD

**Issue by kgilje** [LibraryCarpentry/lc-shell#184]
https://github.com/LibraryCarpentry/lc-shell/blob/ec9d2f905f2ab5c844c0a2555c48361d2e2240d4/setup.md?plain=1#L30

Hello, 
The link intended for putty redirects to : https://www.danielrreynolds.com/
I can't find any reference to putty, instead I recommend pointing to https://www.putty.org/ as it is the package's official website.
It does direct people to : https://www.chiark.greenend.org.uk/~sgtatham/putty/ which is another option for linking.

**Comment by kaitlinnewson** [comment]
Thanks for reporting this @kgilje! I've updated the link to the official website.
