### ISSUE TITLE
Episode 4 grammar edit suggestion

### ISSUE THREAD

**Issue by aidamiro** [LibraryCarpentry/lc-shell#187]
This is a contribution for my instructor training check out.
On episode 4 (Automating the Tedious with Loops) in the Same Symbols, Different Meanings the sentence reads:

If you type > or $ **yourself**, it is an instruction from you **that** the shell to redirect output or get the value of a variable.

Suggested change:

If you type > or $ **in the shell**, it is an instruction from you **to** the shell to redirect output or get the value of a variable.

---

**Comment by CSGeer** [comment]
Would it be better to split it into to lines to make it clearer what the two symbols do? (i.e. "If you type > in the shell..." and "If you type $ in the shell...")
