### ISSUE TITLE
Introduce `tree` in episode 2 (navigating the file system)

### ISSUE THREAD

**Issue by alexander-winkler** [LibraryCarpentry/lc-shell#190]
I was wondering if it is a good idea to introduce, in episode 2, the `tree` command alongside `ls`. It's of course used less frequently but it provides a pretty good visualization of the tree structure of the UNIX file system.

To push it even further, one might use a window multiplexer (`tmux`), split the shell into two halves, and show on one side a dynamically updating tree-structure (`watch -n 0.1 tree`) of the sample directory and apply, on the other, the various file manipulations (`cp`, `mv`, `rm`, `mkdir`, `rmdir`).

One would have to make clear, of course, that `tmux` and `watch` are used in order to make the actual content of the lesson easier to understand and follow and are *not* meant to be learnt by the participants.

I am not sure, of course, if this is compatible with the Carpentries teaching philosophy.

**Comment by kaitlinnewson** [comment]
Hi @alexander-winkler, thanks for your suggestions. One concern I would have about adding `tree` to the lessons is that it's not included in the setups we typically support - with Mac I had to install it with Homebrew, and I don't believe it's included with GitBash (though I don't have an environment setup to test with). 

I think concepts like window splitting or `watch` would be too complex to include in an earlier episode of this lesson and could cause confusion for learners, whether we intend for them to learn about them or not. We also don't generally include concepts or commands unless we plan to explain them to the learner.

**Comment by jmjamison** [comment]
I'd agree with @kaitlinnewson.  This is not a lesson I generally teach but when I do the learners are often new to the concepts.  Adding this might be throwing too much at them in the beginning.
