### ISSUE TITLE
Error due to missing quotation marks in code

### ISSUE THREAD

**Issue by pryn-kb** [LibraryCarpentry/lc-shell#194]
At the "**Working with free text**" page, section "**Grabbing a text, cleaning it up**", we are asked to perform the following line:
`tr [:upper:] [:lower:] < gulliver-noheadfootpunct.txt > gulliver-clean.txt`

However, this gives the error: 
`no matches found: [:upper:]`

This is due to missing quotation marks around [:upper:] and [:lower:].
The correct code is:
`tr '[:upper:]' '[:lower:]' < gulliver-noheadfootpunct.txt > gulliver-clean.txt`

**Comment by kaitlinnewson** [comment]
Thanks for the issue report @pryn-kb! This has been resolved.
