### ISSUE TITLE
The link for the updated location for, Unix shell lessons for librarians has a typo

### ISSUE THREAD

**Issue by wgriffa** [LibraryCarpentry/lc-shell#2]
Hi starting at https://github.com/search?utf8=%E2%9C%93&q=Shell+Lessons+for+Librarians&type=

 data-lessons/library-shell-DEPRECATED
Unix shell lesson for librarians NOW MOVED > https://github.com/LibraryCarpentry/lc-shell  

The "NOW MOVED", link takes you to, https://github.com/LibraryCarpentry/lc-
where it should take you to, https://github.com/LibraryCarpentry/lc-shell

Walter Griffatong

**Comment by weaverbel** [comment]
Fixed
