### ISSUE TITLE
UNIX -> Unix

### ISSUE THREAD

**Issue by tobyhodges** [LibraryCarpentry/lc-shell#200]
_What change I am proposing?_ This lesson uses two alternative spellings: "Unix" and "UNIX". I would like to adopt a consistent spelling throughout the lesson and repository. Based on [what I have read about the history of the project](https://en.wikipedia.org/wiki/Unix#History), I believe "Unix" is the appropriate choice.

_Why am I proposing this change?_ As well as making the lesson and repository internally consistent, this would align this lesson with the Software Carpentry lesson of the same name. The ongoing redesign of The Carpentries website is likely to result in a page listing lessons from all Lesson Programs in one place, so this kind of consistency of style is going to become more important.

If you approve, I will be happy to submit a pull request to make the change.

**Comment by kaitlinnewson** [comment]
This change makes sense to me!

**Comment by emcaulay** [comment]
I agree! Thank you for noticing this detail!
