### ISSUE TITLE
Missing dependency when running Jekyll

### ISSUE THREAD

**Issue by mwhamgenomics** [LibraryCarpentry/lc-shell#206]
After following the setup instructions for the Carpentries workshop template, I ran into Jekyll errors when running `make serve`:

```
$ make serve    
[...]
/usr/local/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
[...]
make: *** [serve] Error 1
```

This can be worked around with `bundle add webrick`, but the permanent fix would be to update this repo's Gemfile in line with the template's one - see https://github.com/carpentries/workshop-template/issues/759.

**Comment by zkamvar** [comment]
Note: This will be fixed once #212 is merged.
