### ISSUE TITLE
Remove hard-wrapped lines to support future translations

### ISSUE THREAD

**Issue by kaitlinnewson** [LibraryCarpentry/lc-shell#253]
### What is the problem?

[See recommendation from the Carpentries translation guide](https://hackmd.io/@joelnitta/SkCSC6ZNT#Requests-for-lesson-authors).

Will need to review all episodes and supplementary materials.

**Comment by jmjamison** [comment]
This would probably be a good pull request.

**Comment by kaitlinnewson** [comment]
Re-opened as some were missed in episode 6.
