### ISSUE TITLE
Find issues to resolve for this lesson

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-shell#3]
This lesson has been migrated here to the Library Carpentry organisation.

All issues that need work are still at the old location:

Find issues to resolve for this lesson here:
https://github.com/data-lessons/library-shell-DEPRECATED/issues

Find issues to resolve *there* and fix them **here**.

**Comment by jt14den** [comment]
Closing b/c the https://github.com/data-lessons/library-shell-DEPRECATED/issues are all closed.
