### ISSUE TITLE
Look at episode 1: 01-intro-shell.md for breaking up into other lessons

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-shell#4]
The `01-intro-shell.md` lesson covers quite a bit of territory: 

* navigating shell 
* cp, mv and mkdir
* creating a loop 
* inspecting files 

I counted at least 10 commands in this one lesson. We  break it up into multiple topical lessons like SWC unix shell.

**Comment by jduckles** [comment]
We're going to do the gross re-org of this and I'll ask @weaverbel to review and merge. Then we'll pitch a few other improvements to those sections.

**Comment by jt14den** [comment]
@jduckles great work! thanks so much.
