### ISSUE TITLE
Creating files in lesson 3

### ISSUE THREAD

**Issue by seb951** [LibraryCarpentry/lc-shell#44]
In lesson 3 (https://librarycarpentry.org/lc-shell/03-working-with-files-and-folders/index.html), the first objective is to "Create files and directories from the command line". But "creating files" is never really introduced or mentioned in the lesson. This will be confusing for a novice learner.

I would recommend either to remove "Create files" from the objectives or have at least one explicit mention on how files can be created (e.g.: by introducing the redirect ">" concept here instead of in lesson 5).

**Comment by libcce** [comment]
Thanks @seb951 for the suggestion! Sorry it has taken so long to get back to you but I've created a PR which I think fixes this.

**Comment by katrinleinweber** [comment]
It's mentioned in passing in https://github.com/LibraryCarpentry/lc-shell/blame/da00f5edbcd4ea7548c3c903f5720f5e29b11128/_episodes/04-loops.md#L30

**Comment by libcce** [comment]
Forgot to link to https://github.com/LibraryCarpentry/lc-shell/pull/67. The PR has been merged which responded to this issue.
