### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [LibraryCarpentry/lc-shell#48]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi Maintainers! - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll make a first pass and add issues currently marked "help-wanted" to the milestone, but please feel free to update the milestone issue list at your convenience. Please let me know if you have any questions!

**Comment by mhayslett** [comment]
I'd like to participate in this development for the sprint.  Also, on a related tangent, I'm installing Git on a new computer this morning and realized that the installation video is no longer current.  It's using 2.7.2 and the latest version is 2.21.0.  I realize it's insane trying to keep up with the newest version, but there are now more installation options that the video doesn't cover:  after the step of adjusting your PATH environment, it wants you to choose the HTTPS transport backend (options are use the OpenSSL library* or the native Windows Secure Channel library [*default options are starred]).  Then the next step is configuring the line ending conversions (options:  checkout Windows-style, commit Unix-style line endings*, checkout as-is, commit Unix-style line endings, or checkout as-is, commit as-is).  Next is configuring the terminal emulator to use with Git Bash which the video _does_ cover, but then the next step is configuring extra options (options:  enable file system caching [checked]; enable Git Credential Manager [checked]; and enable symbolic links [unchecked].  I just kept all the defaults on these--will report if I encounter any problems as I go through the exercises.

**Comment by mhayslett** [comment]
In the second part of the lesson, using ls -l to get the detailed file list, it's not clear whether that's an L or a 1.  Not sure if there's an easy way to clarify since we're using screenshots for the commands.

**Comment by dakane1** [comment]
@ErinBecker Hi Erin, yes we plan on finishing up the checklist by the 7th.  I will be spending next week working on it.  :-)

**Comment by mhayslett** [comment]
@dakane1 (Danielle, hope you don't mind my having horned in on this checklist--it was the only one I could find for the sprint where I felt like I could really contribute.)

**Comment by dakane1** [comment]
@mhayslett Hi Michelle, feel free to add comments.  Our entire goal is to ultimately improve the lesson.  As we go through the checklist we are adding issues for things we want to improve/fix.  I agree with you that "l" and "1" are very hard to decipher.  I need to look at the guidelines to see if they have updated the lesson fonts.  I brought it up as an issue in the last year but haven't had a chance to follow-up.  We have some big plans for the "working with free text" section.

**Comment by libcce** [comment]
I've checked the links and all work except for the PRs I created https://github.com/LibraryCarpentry/lc-shell/pulls Please someone have a look and merge.

**Comment by dakane1** [comment]
Hi Chris,

I can take a look on Monday, currently at a FAIR Data workshop at UCSD.

Best, Danielle

**Comment by jt14den** [comment]
I can look at the challenges & solutions. I went thru already and made sure they are rendering correctly and they are.

**Comment by libcce** [comment]
Setup looks good to go! I created two issues/recommendations to possibly improve setup https://github.com/LibraryCarpentry/lc-shell/issues/57 and https://github.com/LibraryCarpentry/lc-shell/issues/58 (but aren't critical).

**Comment by libcce** [comment]
@jt14den @dakane1 file structure looks clean but I noticed that the files in the zip file for the lesson are listed individually in the data folder. Seems fine but just double checking with you.

**Comment by jt14den** [comment]
@dakane1 @libcce  when thru Ep.2-3 and ran the code to confirm results, challenges and solutions match. Cycling to something else, but if someone wants to look at Ep.4-6 we can check off the two issues related to challenges. I can loop back but prob won't be till next week.

**Comment by libcce** [comment]
Hi @dakane1 @jt14den just went through the exercises and everything checks out except for pg514.txt (Little Women text) is missing from the zip file. It is contained in the same data folder as the zip file https://github.com/LibraryCarpentry/lc-shell/tree/gh-pages/data. I added it to the folder and zipped it again but came up against GitHub's file upload limit. Someone else want to see if they can compress the file further to upload to GitHub? Or we can point to the pg514.txt file in the data dir instead? Or we can deposit it on Zenodo or Figshare? Otherwise, we are set on the exercises.

**Comment by mhayslett** [comment]
I’m working on the challenges & solutions too, but slowly.

Michele

**Comment by elopatin-uc3** [comment]
@libcce @jt14den I've worked through the text, examples, and exercises in Ep. 1-5. The exercises all check out for me too, but I've found one `wc -l` example that shows incorrect count values, a couple of typos, and an exercise setup section which feels like it should have additional underscores for consistency (the `for` loop exercise in Ep. 4). I'll submit a pull request for these tomorrow morning.

**Comment by libcce** [comment]
Thanks @mhayslett and @elopatin-uc3! Nice to have extra eyes have a look! Looking forward to the PRs.

**Comment by jt14den** [comment]
@libcce & @dakane1 I zipped up the little women text and got it to push. I added a PR for it.

**Comment by ErinBecker** [comment]
Awesome work @LibraryCarpentry/lc-git-maintainers  and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by dakane1** [comment]
@ErinBecker Can we close this issue or do you recommend keeping it open?

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3266085

**Comment by libcce** [comment]
Thanks everyone!
