### ISSUE TITLE
Include note about Windows 10 Linux distributions for Shell

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-shell#58]
Per https://www.bleepingcomputer.com/news/microsoft/microsoft-launches-multi-shell-windows-terminal-console-app/
"One of the most anticipated features is the ability to open tabs for multiple console windows in one Windows Terminal window. When opening tabs, you will be able to select the shell you wish to use, which includes the normal CMD shell, PowerShell, and any associated shells from Linux distributions installed via the Windows Subsystem for Linux."

Note on Setup https://librarycarpentry.org/lc-shell/setup.html the associated shell from the Linux distributions on Windows 10.

**Comment by libcce** [comment]
@katrinleinweber since you will be teaching the Shell to maybe Windows users. Do you have any advice on where to mention this in setup?

**Comment by katrinleinweber** [comment]
I haven't tested this myself and I'm not sure. It's mentioned in https://github.com/LibraryCarpentry/lc-shell/blame/2291e170c9c270708ed355e2dfd0b4d8debcf265/_episodes/01-intro-shell.md#L36, though, which we should either update at the same time, or remove.

**Comment by alex-ball** [comment]
I would support including some mention of the WSL option, as it seems a relatively straightforward way to get a fully featured Linux environment on Windows.

Microsoft's help page on this: <https://docs.microsoft.com/en-us/windows/wsl/install-win10>

**Comment by libcce** [comment]
Thanks @alex-ball would you be open to suggesting the text/link to include and where via this issue or via a PR? Thanks and sorry for the delay!
