### ISSUE TITLE
this may be too advanced, but I'm not so sure. What about file permissions & ownership? I noticed there is no mention of this anywhere, yet this is one of the largest issues I face when working in the shell. This is especially important on a server, where multiple users are accessing the machine.

### ISSUE THREAD

**Issue by dakane1** [LibraryCarpentry/lc-shell#63]
this may be too advanced, but I'm not so sure. What about file permissions & ownership? I noticed there is no mention of this anywhere, yet this is one of the largest issues I face when working in the shell. This is especially important on a server, where multiple users are accessing the machine.

And then for automating tasks, there was no mention of the cron. Creating a script is great and is a huge step in the right direction, but if you really want to automate a task, you need to be able to use the cron and schedule a script to run. Maybe this could be added as an addendum?

_Originally posted by @jmcgranahan in https://github.com/LibraryCarpentry/lc-shell/issues/50#issuecomment-500945755_

**Comment by libcce** [comment]
HI @jmcgranahan! There is a section on creating a bash script https://librarycarpentry.org/lc-shell/04-loops/index.html This may be a section where we can point to a tutorial on creating cron jobs just like how we point to a tutorial on bash scripts? Do you have recommendations regarding helpful cron tutorials?

And I've seen instructors use a slide to explain the output of ls -lh and explain file permissions. I've done this as well. I think it would be helpful. @shlake has a slide that maybe she can share?

**Comment by jmcgranahan** [comment]
@libcee  here's a YouTube video: https://www.youtube.com/watch?v=7MFMnsnfBJs, and here a a pretty good written tutorial from OSTechNix: https://www.ostechnix.com/a-beginners-guide-to-cron-jobs/

**Comment by dakane1** [comment]
I think maybe an addendum might work, I guess I'm wondering how many librarians have access to servers to even run into this problem.  I know my library IT keeps the servers pretty much locked down.  So if it was something that could be left out or added in as needed and depending on the audience that might work.

**Comment by libcce** [comment]
@dakane1 @jmcgranahan regarding cron, we can point to a resource with more info/a tutorial but probably nothing more.

**Comment by jt14den** [comment]
@dakane1 you can also include an aside or note in the lesson using the callout blockquote http://carpentries.github.io/lesson-example/04-formatting/#callout. I think this was designed for this type of thing. Also check out the LC instructor notes for this lesson (which I think are copied from SWC) where we explain not including permissions/ownership for the sake of time: https://librarycarpentry.org/lc-shell/guide/index.html. If we create an addendum we should update the instructor guide. The issue #51 is open for us to take a look at that and make sure the guide corresponds to the lesson.

**Comment by kaitlinnewson** [comment]
Closing this issue as both permissions and cron tasks are more advanced topics that would be difficult for most instructors to fit into the lesson materials, and would not apply to many users that don't have server access (as noted above). Please comment and we can revisit if there is a case for including these concepts.
