### ISSUE TITLE
Feedback on episodes three and five

### ISSUE THREAD

**Issue by ErinBecker** [LibraryCarpentry/lc-shell#66]
Submitted by email as part of Instructor Training checkout:

Here is my feedback/contribution on the Library Carpentry: The Shell Lesson, specifically in episode three and five.

The tip on Canceling Commands is confusing in its current section.

It references cancelling the previous command to print the contents of a book, but the output is on the screen almost instantly (or in a few instances takes 1-2 seconds).

This causes confusion for learners as they read through the lesson/follow along because nothing happens, when they "cancel".

This tip would be more helpful in episode five in the section on grep as it takes more time for the shell to process and search. The lines of text "cascade" by in the window like is mentioned in episode three. The tip would be helpful after this script:

$ grep -iwE 'fr[ae]nc[eh]' *.tsv

This gives learners time to input ctrl + c and see the print stop. They also know what to expect as they saw the full printout of grep earlier.

**Comment by libcce** [comment]
Thank you @ErinBecker for forwarding this on and thank whoever submitted it 😄 I've created https://github.com/LibraryCarpentry/lc-shell/pull/72 which hopefully helps? @annaoates @dakane1 what do you think?
