### ISSUE TITLE
Reference about gulliver.txt file in 06 working with free text

### ISSUE THREAD

**Issue by morskyjezek** [LibraryCarpentry/lc-shell#79]
Episode 6 currently states: "We’re going to work with the gulliver.txt file we made in the previous lesson." Has it been considered to make this more precise by saying something like "We're going to work with the gulliver.txt file, which we made from the 829-0.txt file in Episode 3, Working with files and folders." (Current formulation is slightly confusing since the previous episode actually renames a chapter from Little Women. I see there were some earlier issues raised about this file so thought this may be a confusing bit for others as well.

**Comment by dakane1** [comment]
Hi @morskyjezek we are actually starting a project to overall Episode 6 but in the meantime I will take a look at this and see if I can make the text clearer for instructors.

**Comment by morskyjezek** [comment]
Oh, okay. I hadn't realized there was a larger revision in motion already, but good to know :)

**Comment by morskyjezek** [comment]
Happy to close the issue if there's other work already in motion.

**Comment by dakane1** [comment]
@morskyjezek hehe we aren't that fast, so far we just have big plans and are doing the project planning.  It's still a good idea to make the change for those teaching the lesson in the meantime. Bring stuff up, we will always tell you why we make certain decisions.
