### ISSUE TITLE
Code in Lesson 5 Counting and mining does not work

### ISSUE THREAD

**Issue by mtthsdzwn** [LibraryCarpentry/lc-shell#85]
See lesson 5 'Counting and mining with the shell', section 'Automatically adding a date prefix'.

The example in the text uses `date -I`. This does not work on my system (MacOS 10.14.5, GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)). I was unable to check for other systems. I find a reference to the `-I` flag [here](http://man7.org/linux/man-pages/man1/date.1.html), but not [here](https://linux.die.net/man/1/date).

Something similar can be achieved by `date "+%Y %m %d"`. But then it might be necessary to explain the formatting commands.

**Comment by alex-ball** [comment]
Yes, it looks like the `--iso-8601` option is available in `date` from GNU coreutils (thus on Linux, WSL, etc. and via Homebrew) but not in the version available by default on macOS.

See, for example, this [question about the `--iso-8601` option](https://unix.stackexchange.com/questions/164826/date-command-iso-8601-option) on StackExchange.

**Comment by libcce** [comment]
I think a note inline would be fine for now. Can we point to more info about formatting commands as well? @dakane1 what do you think?

**Comment by dakane1** [comment]
Hi @libcce I agree I think an inline note with a pointer to more info would be good for now.  We can see how it goes, if more people have questions we can always look at it again.

**Comment by konrad** [comment]
I also stumble into this issue during a lesson. Would be great if this could be fixed e.g. by adding the adapted call from @mtthsdzwn for Mac user or in general although not a elegant as call with "-I". Thanks!
