### ISSUE TITLE
Providing sed solutions in episode 6: Working with Free Text

### ISSUE THREAD

**Issue by scottcpeterson** [LibraryCarpentry/lc-shell#92]
@drjwbaker I wasn't able to find a solution to the sed challenges in the working with free text lesson ( removing smart quotes using sed). What I found didn't work, and I am not sure if it is because I am on a Windows machine or not. I think it is important for learners to understand how to find answers online, but I also think we should be providing answers to solutions too.

**Comment by drjwbaker** [comment]
Okay. Thanks for the note. Do you have a proposed solution you could offer?

**Comment by ostephens** [comment]
Would a compromise be to put solution(s) in the instructor notes rather than directly in the text? This provides a way of introducing the idea it is normal to have to search for solutions to problems online while ensuring that the solution is available during a training session.

Either way, if there are different solutions on different Operating Systems I think this would be worth noting in the challenge text to point users in the right direction.

**Comment by libcce** [comment]
I like this idea from @ostephens to put the solution in the instructor notes for now. Having said this, I haven't worked out a solution but I believe @jcoliver was working on this section during the recent sprint and at least provided some additional help for the learner. @jcoliver do you have a solution you can share?

**Comment by scottcpeterson** [comment]
I couldn't find a solution that worked on my Windows machine, so I don't have a solution for this challenge. The one problem I have with putting the solution in the instructor notes is that I don't know how often this section actaully gets taught in a workshop--I didn't have the time to get to it---and other instructors have pointed out to me that they end up directing students to this section to follow up on as homework, or on their own time. That means there will be no instructor there to give them the solution most of the time, and unless they end up looking at the instructor notes section, they might not be able to find the solution. Also, on another note, how do you acutally teach this section? It says, "Before going any further, speak to the person next to you and choose which type of text you’d like to work on together", which lends me to think of this as one big challenge (and 40 minutes are alotted for this), yet before they get to the sed quotes challenge, there is stuff to teach. This seems very confusing to me.

**Comment by dakane1** [comment]
@scottcpeterson We started a project to work on episode 6 for exactly the reasons you brought up.  It always seemed odd to me that we dump them into one big challenge without introducing them to the concepts first.  We hope to solve that problem and I plan to start working on it as soon as soon as I finish a big data cleanup project.

**Comment by scottcpeterson** [comment]
Thanks @dakane1. That's good to know.

**Comment by jcoliver** [comment]
Whoa, @libcce , that was _last_ year's sprint where I worked on this. The solution I proposed in is in the (closed) #11 .

**Comment by alex-ball** [comment]
@scottcpeterson: is the problem on Windows to do with encodings? If you change the code page to UTF-8 (or some approximation of it) does it work then?

```
chcp 65001
```

If you have Unicode support, then you can get remove all quotes with this:

```
sed -Ee 's/[“”‘’]//g' < gulliver-clean.txt > gulliver-noquotes.txt
```

Though if you care about retaining apostrophes (as opposed to single quote marks) then you really need a proper parser, but the following only has one false negative (`‘our brother tom has just got the piles’`):

```
sed -Ee 's/[“”‘]//g; s/([^s])’(\W)/\1\2/g' < gulliver-clean.txt > gulliver-noquotes.txt
```

**Comment by scottcpeterson** [comment]
Hi Alex,



Sorry about taking so long to get back to you. I can’t figure out how to
change the code pages to UTF-8 in windows, as the chcp 65001 command
doesn’t seem to work in Git Bash. Using the sed commands below, the quotes
don’t seem to be removed from the files.



Best,



Scott



*From:* Alex Ball [mailto:notifications@github.com]
*Sent:* Tuesday, August 20, 2019 2:38 AM
*To:* LibraryCarpentry/lc-shell
*Cc:* Scott Peterson; Mention
*Subject:* Re: [LibraryCarpentry/lc-shell] Providing sed solutions in
episode 6: Working with Free Text (#92)



@scottcpeterson <https://github.com/scottcpeterson>: is the problem on
Windows to do with encodings? If you change the code page to UTF-8 (or some
approximation of it) does it work then?

chcp 65001



If you have Unicode support, then you can get remove all quotes with this:

sed -Ee 's/[“”‘’]//g' < gulliver-clean.txt > gulliver-noquotes.txt



Though if you care about retaining apostrophes (as opposed to single quote
marks) then you really need a proper parser, but the following only has one
false negative (‘our brother tom has just got the piles’):

sed -Ee 's/[“”‘]//g; s/([^s])’(\W)/\1\2/g' < gulliver-clean.txt >
gulliver-noquotes.txt



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibraryCarpentry/lc-shell/issues/92?email_source=notifications&email_token=AD4OGGIQS3GAIHMS4RQO7DDQFO3OPA5CNFSM4IKDST62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4VWDQA#issuecomment-522936768>,
or mute the thread

**Comment by alex-ball** [comment]
Sorry, that only seems to work at the regular Windows command prompt.

In the Git Bash window, type this:

```bash
locale
```

I currently have the following set (which is why it works for me):

```bash
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

If you don't get that, change the language like this:

```bash
LANG='en_US.UTF-8'
```

Or whatever suits you best. You can see the options available by right-clicking the window, selecting 'Options...' and finding the 'Text' pane: the available locales and character sets are in the dropdowns at the bottom.

(Answer found via [StackOverflow](https://stackoverflow.com/a/36692549/11966865).)

**Comment by scottcpeterson** [comment]
Hi Alex,



My setting are all UTF-8. When I run the commands you sent, I don’t get an
error message, but the quotes are not removed from the files. Maybe someone
should try this on another windows machine using Git Bash to see if it
might just be something with my setup.



Best,



Scott



*From:* Alex Ball [mailto:notifications@github.com]
*Sent:* Friday, September 06, 2019 1:58 AM
*To:* LibraryCarpentry/lc-shell
*Cc:* Scott Peterson; Mention
*Subject:* Re: [LibraryCarpentry/lc-shell] Providing sed solutions in
episode 6: Working with Free Text (#92)



Sorry, that only seems to work at the regular Windows command prompt.

In the Git Bash window, type this:

locale

I currently have the following set (which is why it works for me):

LANG=en_US.UTF-8

LC_CTYPE="en_US.UTF-8"

LC_NUMERIC="en_US.UTF-8"

LC_TIME="en_US.UTF-8"

LC_COLLATE="en_US.UTF-8"

LC_MONETARY="en_US.UTF-8"

LC_MESSAGES="en_US.UTF-8"

LC_ALL=

If you don't get that, change the language like this:

LANG='en_US.UTF-8'

Or whatever suits you best. You can see the options available by
right-clicking the window, selecting 'Options...' and finding the 'Text'
pane: the available locales and character sets are in the dropdowns at the
bottom.

(Answer found via StackOverflow
<https://stackoverflow.com/a/36692549/11966865>.)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibraryCarpentry/lc-shell/issues/92?email_source=notifications&email_token=AD4OGGIES3V6RWSFKB5EYXDQIILQTA5CNFSM4IKDST62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6CHBCA#issuecomment-528773256>,
or mute the thread

**Comment by dakane1** [comment]
I can try this on machine, but not until next week.  I have next Thursday blocked out to do some LC-Unix work.

**Comment by alex-ball** [comment]
In the meantime, the only other things I can suggest are:

- double-check that `gulliver-clean.txt` is also UTF-8 encoded;
- copy/paste the quote marks from `gulliver-clean.txt` into your Bash window in place of the ones in my comment above;
- if `gulliver-clean.txt` is definitely UTF-8 encoded, you can use the hexcodes as below.

```bash
sed -Ee 's/(\xe2\x80\x9c|\xe2\x80\x9d|\xe2\x80\x98|\xe2\x80\x99)//g' < gulliver-clean.txt > gulliver-noquotes.txt
```

**Comment by alex-ball** [comment]
Okay, we need to get all Reproducible Research on this.

Aim: get a SED solution working reliably on Windows.

Method:

1. Download fresh copy of shell-lesson ZIP, and extract.
2. Install (or upgrade to) latest Git for Windows.
3. In the shell lesson directory, run the following in Git Bash.

```
$ bash --version
$ sed --version
$ md5sum 829-0.txt
$ sed -Ee 's/[“”‘’]//g' < 829-0.txt > gulliver-noquotes.txt
$ md5sum gulliver-noquotes.txt
```

Results: please report OS; version of Git for Windows installed; whether you chose to use MinTTY (default) or CMD.exe during Git installation; versions of bash and sed; and the two MD5 checksums.

I will combine my 3 reports so far into one as the results are identical:

- **OS:** MS Windows 10 Pro / Windows 7 Home Premium
- **Git for Windows:** v2.23.0 64-bit
- **Terminal used:** MinTTY (both) / CMD.exe (Win 7 only)
- **Bash:** v.4.4.23
- **SED:** GNU sed v4.7
- **Checksum of 829-0.txt:** 276fbd439bfbff7559b8a7285de1ae79
- **Checksum of gulliver-noquotes.txt:** 1a50dc926a4cbb605c78999462b048f3

Since CMD.exe does not have a Unicode font by default, this is what the sed line looks like in that environment:
![sed-quotes-screenshot](https://user-images.githubusercontent.com/1890395/64855280-6fcfec00-d617-11e9-8ecd-ad48b43f345a.png)

The above checksum (1a50...) corresponds to the successful removal of curly quote marks (not any straight quotes in the header or footer).

**Comment by dakane1** [comment]
@alex-ball I was going to try to get to this today but the work day was crazy.  I will give it a try on Monday.

**Comment by dakane1** [comment]
OS: Windows 10
Git for Windows: v2.23.0 64 bit
Terminal used: MinTTY
bash --version GNU Bash 4.4.23 64 bit
sed --version 4.7

![kaned_git_smartquotes](https://user-images.githubusercontent.com/28713952/64984478-ce93a080-d877-11e9-870b-f09e29b2a5c8.jpg)

I think that after I went through this process I understand why we might be having differences.  I was running sed -Ee.... after the entire process in episode 6, aka after sorting and counting versus running it from 829-0.txt.   The challenge assumes that you are trying to get rid of the smart quotes after running through the entire cleaning process.  Maybe it is the challenge that needs to be reworded or an actual answer provided.  I.e. that the sed -Ee...would need to be run at the start of the cleaning process and not at the end, mainly because it doesn't work once you have counted and sorted the text.

**Comment by alex-ball** [comment]
Okay, so we know that the sed command itself works. It's a matter of identifying where the break in the chain occurs. If you will humour a bit more testing, we can do that fairly easily.

In the lines below I provide two different checksums depending on whether the Windows line endings (CR LF) are preserved by `sed` or converted to UNIX line endings (LF). I believe it goes like this:

| Mode | Command | Windows | UNIX-like |
| --- | --- | --- | --- |
| Text | `sed ...` | convert to LF | preserve CRLF |
| Binary | `sed -b ...` | preserve CRLF* | preserve CRLF |

\* There are reports of this being buggy in some versions/circumstances, but I did not see any problems with Git Bash on Windows 10.

For completeness I'll start at the beginning:

```bash
$ md5sum 829-0.txt
```
CRLF: 276fbd439bfbff7559b8a7285de1ae79

```bash
$ sed '9352,9714d' 829-0.txt | md5sum
```
LF: 4333e45d0bc633a769b2e5c29af0527b
CRLF: 9f819fb929c04dbbb62128a4405b3922

```bash
$ sed '9352,9714d' 829-0.txt | sed '1,37d' | md5sum
```
LF: 9242f3925ec5544d43687a062eeb87bf
CRLF: 4c90daf1a402689bc2787c811f6ab814

```bash
$ sed '9352,9714d' 829-0.txt | sed '1,37d' | tr -d [:punct:] | md5sum
```
LF: 3397765b1692669f9b266e4207c05f7b
CRLF: ad0b251616798685608c481a7c67d487

```bash
$ sed '9352,9714d' 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr [:upper:] [:lower:] | md5sum
```
LF: d067beda44fbb5aeab903e71b8465fe5
CRLF: c27e4d9da85a284abce0e35942b66d32

```bash
sed '9352,9714d' 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr [:upper:] [:lower:] | sed -Ee 's/[“”‘’]//g' | md5sum
```
LF: 0d070535b88d4ecb6eea5375ccb5be68
CRLF: fcadb4b0ce4904cfd2087de3a18b9198

If you match all the way to the bottom, then everything has worked. If not, then please could you let me know where the mismatch occurred.

(It should still work after the counting and sorting as well, but you wouldn't want to do it then because words that were previously different will be now be the same, but they won't be counted together.)

@scottcpeterson, please could you try this as well on your setup *without* upgrading anything as previously suggested. It may be that there is a bug in earlier versions, in which case it would be good to document which versions to avoid.

**Comment by alex-ball** [comment]
@dakane1, no I don't think that's it. It should still work after the counting and sorting as well, but you wouldn't want to do it then because words that were previously different will be now be the same, but they won't be counted together.

From your screenshot it looks like your quotes have not pasted in correctly: with the Lucida Console font in MinTTY they should be distinct:
![sed-lucida-console](https://user-images.githubusercontent.com/1890395/65035800-036c2a00-d942-11e9-9dc2-7079cfbe8e4d.png)

**Comment by alex-ball** [comment]
On my Windows 10 (10.0.18362) I can input the quote marks with

- Alt + 8216 = `‘`
- Alt + 8217 = `’`
- Alt + 8220 = `“`
- Alt + 8221 = `”`

**Comment by dakane1** [comment]
Could someone help Alex with more testing?  I'm leaving in a couple of hours for a cruise to Alaska.  Though if this isn't super urgent I can do the testing once I return on the 30th.

**Comment by scottcpeterson** [comment]
Hi Alex,



I haven’t upgraded anything, and everything checks out until the last command:

sed '9352,9714d' 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr
[:upper:] [:lower:] | sed -Ee 's/[“”‘’]//g' | md5sum



The answer I get for that command is

LF: d4501f76152305908340bbd90c203e40



Best,



Scott



*From:* Alex Ball [mailto:notifications@github.com]
*Sent:* Tuesday, September 17, 2019 3:45 AM
*To:* LibraryCarpentry/lc-shell
*Cc:* Scott Peterson; Mention
*Subject:* Re: [LibraryCarpentry/lc-shell] Providing sed solutions in
episode 6: Working with Free Text (#92)



Okay, so we know that the sed command itself works. It's a matter of
identifying where the break in the chain occurs. If you will humour a bit
more testing, we can do that fairly easily.

In the lines below I provide two different checksums depending on whether
the Windows line endings (CR LF) are preserved by sed or converted to UNIX
line endings (LF). I believe it goes like this:

*Mode*

*Command*

*Windows*

*UNIX-like*

Text

sed ...

convert to LF

preserve CRLF

Binary

sed -b ...

preserve CRLF*

preserve CRLF

* There are reports of this being buggy in some versions/circumstances, but
I did not see any problems with Git Bash on Windows 10.

For completeness I'll start at the beginning:

$ md5sum 829-0.txt

CRLF: 276fbd439bfbff7559b8a7285de1ae79

$ sed '9352,9714d' 829-0.txt | md5sum

LF: 4333e45d0bc633a769b2e5c29af0527b
CRLF: 9f819fb929c04dbbb62128a4405b3922

$ sed '9352,9714d' 829-0.txt | sed '1,37d' | md5sum

LF: 9242f3925ec5544d43687a062eeb87bf
CRLF: 4c90daf1a402689bc2787c811f6ab814

$ sed '9352,9714d' 829-0.txt | sed '1,37d' | tr -d [:punct:] | md5sum

LF: 3397765b1692669f9b266e4207c05f7b
CRLF: ad0b251616798685608c481a7c67d487

$ sed '9352,9714d' 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr
[:upper:] [:lower:] | md5sum

LF: d067beda44fbb5aeab903e71b8465fe5
CRLF: c27e4d9da85a284abce0e35942b66d32

sed '9352,9714d' 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr
[:upper:] [:lower:] | sed -Ee 's/[“”‘’]//g' | md5sum

LF: 0d070535b88d4ecb6eea5375ccb5be68
CRLF: fcadb4b0ce4904cfd2087de3a18b9198

If you match all the way to the bottom, then everything has worked. If not,
then please could you let me know where the mismatch occurred.

(It should still work after the counting and sorting as well, but you
wouldn't want to do it then because words that were previously different
will be now be the same, but they won't be counted together.)

@scottcpeterson <https://github.com/scottcpeterson>, please could you try
this as well on your setup *without* upgrading anything as previously
suggested. It may be that there is a bug in earlier versions, in which case
it would be good to document which versions to avoid.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibraryCarpentry/lc-shell/issues/92?email_source=notifications&email_token=AD4OGGNXWOK5CCMYYPV7NLDQKCYKTA5CNFSM4IKDST62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD64DQII#issuecomment-532166689>,
or mute the thread

**Comment by alex-ball** [comment]
@scottcpeterson, thanks for testing. Sorry you saw a message I retracted once I actually looked at  Danielle's checksum and realised it was wrong. This is still very interesting: the `sed` operation definitely did something, but not the right thing.

At that point in the chain, there are no straight quotes so if you were having the same problem as Danielle the checksum would still be d067beda44fbb5aeab903e71b8465fe5.

Could you do a diff for me to see what it actually did?

```bash
$ sed '9352,9714d' < 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr [:upper:] [:lower:] > gulliver-clean.txt
$ sed '9352,9714d' < 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr [:upper:] [:lower:] | sed -Ee "s/[“”‘’]//g" > gulliver-noquotes.txt
$ diff gulliver-clean.txt gulliver-noquotes.txt | head -n32
```

**Comment by alex-ball** [comment]
@scottcpeterson, never mind, I see what has happened. It has removed the curly double quotes but not the curly single quotes. That is odd.

Do the curly single quotes look right on your screen?

**Comment by scottcpeterson** [comment]
Hi Alex,



Here is the output from that last command:



$ diff gulliver-clean.txt gulliver-noquotes.txt | head -n32



It looks like the apostrophes were pulled from the gulliver-clean.txt



1c1

<                             gulliver’s travels

---

>                             gullivers travels

7c7

<                       dean of st patrick’s dublin

---

>                       dean of st patricks dublin

21c21

< mother’s side  about three years ago mr gulliver growing weary of the

---

> mothers side  about three years ago mr gulliver growing weary of the

42c42

< by the advice of several worthy persons to whom with the author’s

---

> by the advice of several worthy persons to whom with the authors

88c88

< knowledge being in england during some part of her majesty’s reign she

---

> knowledge being in england during some part of her majestys reign she

125c125

< of law books the young nobility’s education entirely changed the

---

> of law books the young nobilitys education entirely changed the

271c271

< by a violent storm to the northwest of van diemen’s land  by an

---

> by a violent storm to the northwest of van diemens land  by an

276c276

< the seamen spied a rock within half a cable’s length of the ship but the

---

> the seamen spied a rock within half a cables length of the ship but the



*From:* Alex Ball [mailto:notifications@github.com]
*Sent:* Thursday, September 19, 2019 1:50 AM
*To:* LibraryCarpentry/lc-shell
*Cc:* Scott Peterson; Mention
*Subject:* Re: [LibraryCarpentry/lc-shell] Providing sed solutions in
episode 6: Working with Free Text (#92)



@scottcpeterson <https://github.com/scottcpeterson>, thanks for testing.
Sorry you saw a message I retracted once I actually looked at Danielle's
checksum and realised it was wrong. This is still very interesting: the sed
operation definitely did something, but not the right thing.

At that point in the chain, there are no straight quotes so if you were
having the same problem as Danielle the checksum would still be
d067beda44fbb5aeab903e71b8465fe5.

Could you do a diff for me to see what it actually did?

$ sed '9352,9714d' < 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr
[:upper:] [:lower:] > gulliver-clean.txt



$ sed '9352,9714d' < 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr
[:upper:] [:lower:] | sed -Ee "s/[“”‘’]//g" > gulliver-noquotes.txt



$ diff gulliver-clean.txt gulliver-noquotes.txt | head -n32

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibraryCarpentry/lc-shell/issues/92?email_source=notifications&email_token=AD4OGGIU6XD3COUE4CVQNM3QKM4LRA5CNFSM4IKDST62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7CXF5Q#issuecomment-533033718>,
or mute the thread

**Comment by scottcpeterson** [comment]
The double quotes are still in the gulliver-noquotes.txt. Below is a
section from that .txt file.



“golbasto momarem evlame gurdilo shefin mully ully gue most mighty

emperor of lilliput delight and terror of the universe whose dominions

extend five thousand blustrugs about twelve miles in circumference to

the extremities of the globe monarch of all monarchs taller than the

sons of men whose feet press down to the centre and whose head strikes

against the sun at whose nod the princes of the earth shake their knees

pleasant as the spring comfortable as the summer fruitful as autumn

dreadful as winter his most sublime majesty proposes to the

manmountain lately arrived at our celestial dominions the following

articles which by a solemn oath he shall be obliged to perform—



“1st the manmountain shall not depart from our dominions without our

license under our great seal



“2d he shall not presume to come into our metropolis without our

express order at which time the inhabitants shall have two hours

warning to keep within doors



“3d the said manmountain shall confine his walks to our principal high

roads and not offer to walk or lie down in a meadow or field of corn



“4th as he walks the said roads he shall take the utmost care not to

trample upon the bodies of any of our loving subjects their horses or

carriages nor take any of our subjects into his hands without their own

consent



“5th if an express requires extraordinary despatch the manmountain

shall be obliged to carry in his pocket the messenger and horse a six

days journey once in every moon and return the said messenger back if

so required safe to our imperial presence



“6th he shall be our ally against our enemies in the island of blefuscu

and do his utmost to destroy their fleet which is now preparing to

invade us



*From:* Alex Ball [mailto:notifications@github.com]
*Sent:* Thursday, September 19, 2019 2:00 AM
*To:* LibraryCarpentry/lc-shell
*Cc:* Scott Peterson; Mention
*Subject:* Re: [LibraryCarpentry/lc-shell] Providing sed solutions in
episode 6: Working with Free Text (#92)



@scottcpeterson <https://github.com/scottcpeterson>, never mind, I see what
has happened. It has removed the curly double quotes but not the curly
single quotes. That is odd.

Do the curly single quotes look right on your screen?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibraryCarpentry/lc-shell/issues/92?email_source=notifications&email_token=AD4OGGIS5Q4D33Y4QUS2IH3QKM5Q7A5CNFSM4IKDST62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7CYCWI#issuecomment-533037401>,
or mute the thread

**Comment by scottcpeterson** [comment]
Here is that text in Gulliver-noquotes.txt with line numbers to make it
easier to find:



  1031  “golbasto momarem evlame gurdilo shefin mully ully gue most mighty

  1032  emperor of lilliput delight and terror of the universe whose
dominions

  1033  extend five thousand blustrugs about twelve miles in circumference
to

  1034  the extremities of the globe monarch of all monarchs taller than the

  1035  sons of men whose feet press down to the centre and whose head
strikes

  1036  against the sun at whose nod the princes of the earth shake their
knees

  1037  pleasant as the spring comfortable as the summer fruitful as autumn

  1038  dreadful as winter his most sublime majesty proposes to the

  1039  manmountain lately arrived at our celestial dominions the following

  1040  articles which by a solemn oath he shall be obliged to perform—

  1041

  1042  “1st the manmountain shall not depart from our dominions without our

  1043  license under our great seal

  1044

  1045  “2d he shall not presume to come into our metropolis without our

  1046  express order at which time the inhabitants shall have two hours

  1047  warning to keep within doors

  1048

  1049  “3d the said manmountain shall confine his walks to our principal
high

  1050  roads and not offer to walk or lie down in a meadow or field of corn

  1051

  1052  “4th as he walks the said roads he shall take the utmost care not to

  1053  trample upon the bodies of any of our loving subjects their horses
or

  1054  carriages nor take any of our subjects into his hands without their
own

  1055  consent

  1056

  1057  “5th if an express requires extraordinary despatch the manmountain

  1058  shall be obliged to carry in his pocket the messenger and horse a
six

  1059  days journey once in every moon and return the said messenger back
if

  1060  so required safe to our imperial presence

  1061

  1062  “6th he shall be our ally against our enemies in the island of
blefuscu

  1063  and do his utmost to destroy their fleet which is now preparing to

  1064  invade us



*From:* Scott Peterson [mailto:speterso@berkeley.edu]
*Sent:* Thursday, September 19, 2019 9:35 AM
*To:* 'LibraryCarpentry/lc-shell'; 'LibraryCarpentry/lc-shell'
*Cc:* 'Mention'
*Subject:* RE: [LibraryCarpentry/lc-shell] Providing sed solutions in
episode 6: Working with Free Text (#92)



The double quotes are still in the gulliver-noquotes.txt. Below is a
section from that .txt file.



“golbasto momarem evlame gurdilo shefin mully ully gue most mighty

emperor of lilliput delight and terror of the universe whose dominions

extend five thousand blustrugs about twelve miles in circumference to

the extremities of the globe monarch of all monarchs taller than the

sons of men whose feet press down to the centre and whose head strikes

against the sun at whose nod the princes of the earth shake their knees

pleasant as the spring comfortable as the summer fruitful as autumn

dreadful as winter his most sublime majesty proposes to the

manmountain lately arrived at our celestial dominions the following

articles which by a solemn oath he shall be obliged to perform—



“1st the manmountain shall not depart from our dominions without our

license under our great seal



“2d he shall not presume to come into our metropolis without our

express order at which time the inhabitants shall have two hours

warning to keep within doors



“3d the said manmountain shall confine his walks to our principal high

roads and not offer to walk or lie down in a meadow or field of corn



“4th as he walks the said roads he shall take the utmost care not to

trample upon the bodies of any of our loving subjects their horses or

carriages nor take any of our subjects into his hands without their own

consent



“5th if an express requires extraordinary despatch the manmountain

shall be obliged to carry in his pocket the messenger and horse a six

days journey once in every moon and return the said messenger back if

so required safe to our imperial presence



“6th he shall be our ally against our enemies in the island of blefuscu

and do his utmost to destroy their fleet which is now preparing to

invade us



*From:* Alex Ball [mailto:notifications@github.com]
*Sent:* Thursday, September 19, 2019 2:00 AM
*To:* LibraryCarpentry/lc-shell
*Cc:* Scott Peterson; Mention
*Subject:* Re: [LibraryCarpentry/lc-shell] Providing sed solutions in
episode 6: Working with Free Text (#92)



@scottcpeterson <https://github.com/scottcpeterson>, never mind, I see what
has happened. It has removed the curly double quotes but not the curly
single quotes. That is odd.

Do the curly single quotes look right on your screen?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibraryCarpentry/lc-shell/issues/92?email_source=notifications&email_token=AD4OGGIS5Q4D33Y4QUS2IH3QKM5Q7A5CNFSM4IKDST62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7CYCWI#issuecomment-533037401>,
or mute the thread

**Comment by alex-ball** [comment]
Sorry, yes, of course you're right. I got the same checksum with this:

```bash
sed '9352,9714d' < 829-0.txt | sed '1,37d' | tr -d [:punct:] | tr [:upper:] [:lower:] | sed -Ee "s/[‘’]//g" | md5sum
```
and then got confused.

It's still quite odd that one set works and the other doesn't.

The problem with the `\xNN` notation for hex codes is that support for it is patchy across versions (I don't think the Mac version currently supports it, for example).

Does it work any better as a shell script? Here is one (zipped) for turning `829-0.txt` into `gulliver-noquotes.txt`:
[remove-quotes.zip](https://github.com/LibraryCarpentry/lc-shell/files/3632700/remove-quotes.zip)

**Comment by scottcpeterson** [comment]
It worked using the shell script. The quotes are gone from the lines I sent you earlier.

**Comment by alex-ball** [comment]
Excellent, so we have a working solution. It seems the problem lies in entering the right characters on the command line without them being converted to (or misread as) something else.

We introduce Bash scripts in episode 4, so it would not be too much of a stretch to suggest that people use a Bash script to solve this issue. Possibly this makes a good learning point about how to deal with non-ASCII characters more generally.

For extra marks they could get rid of the remaining dashes as well. :-)

**Comment by jt14den** [comment]
Following up on this @alex-ball, @scottcpeterson & @dakane1. Is there a path forward on this issue? The challenge that kicked off this thread unearths a lot of complexity around character encoding that seems beyond a novice level. We could change the challenge into a callout instead giving learners a heads up on the variation in diff. character types and OS's.

**Comment by jt14den** [comment]
@alex-ball can you give it a try?
