### ISSUE TITLE
macOS Catalina uses zsh instead of bash by default

### ISSUE THREAD

**Issue by alex-ball** [LibraryCarpentry/lc-shell#96]
It seems that macOS 10.15 (Catalina), due for general release Fall 2019, uses [zsh instead of bash](https://support.apple.com/en-us/HT208050) by default. I don't think the lesson strays into areas where the syntax differs between bash and zsh, but the Setup page will need to be updated for accuracy at least.

I don't have a Mac so not I'm not ideally placed to comment on whether it would be better for Catalina users to do the lesson under zsh or to provide instructions on how to switch to bash. (Will people need to install it? If so, can they install the latest bash instead of the current default version?)

**Comment by karenword** [comment]
Relevant point added as a contribution for checkout, sent via email:

"As part of helping at a recent Carpentries workshop at University of Toronto Scarborough, I noticed that Bash was replaced with zsh as the default shell in 2019 for Apple users (according to this report).

Would it be worthwhile to indicate this change on the Library Carpentry UNIX Shell lesson? (https://librarycarpentry.org/lc-shell/setup.html or the Configuration Problems and Solutions wiki page)"
