### ISSUE TITLE
Unclear on reference to PowerShell in Introduction

### ISSUE THREAD

**Issue by pybrarian** [LibraryCarpentry/lc-shell#99]
I just submitted a PR ( #98 ) for a typo in this area, but I am curious about it's meaning. In the introduction under "Where is my shell?" there is the following:

>"For Windows users, popular shells such as Cygwin or Git Bash provide a Unix-like interface,   but may need to be installed separately. In Windows 10, the Power Shell natively provides that functionality."

It is unclear to me what is meant by PowerShell natively supports that functionality? Given the previous sentence I read it as saying that PowerShell provides a Unix-like interface. While it provides some aliases for popular Unix commands (`ls` for `Get-ChildItem`/`dir` ), it does not implement a full bash shell, including commands used later in the lessons (i.e. there's no `sed` or `grep`).

I worry it could confuse learners, but I may just be misinterpreting it.

**Comment by jmjamison** [comment]
This may not be the appropriate place to ask but shouldn't the linux subsystem for windows subsystem be added?  Someplace.

**Comment by jmjamison** [comment]
I'd agree that WIndows PowerShell doesn't provide the functionality.  I never use it myself and just tried some commands.  I use Linux subsystem myself.  
I think mentioning PowerShell might be confusing.  GitBash would be a better choice unless people have the subsystem installed.  I'd be interested to know what others think and if this should be a pull request.

**Comment by hoytpr** [comment]
I'd definitely remove that reference to Power she'll. Also Cygwin as we don't use that in any formalized workshops I am aware of (even though I like it more than Gitbash). 

The WSL is also still a problem unless we all decide to spend a day teaching learners how to install the WSL, then the same version of Ubuntu offered through Google Play. I use Windows a lot (I'm not a Windows fanatic), but anything we can run through Gitbash will simplify our setups for the learners. IMHO.
Peter
